[package]
name = "lib-dmg-01"
version = "0.0.1"
authors = ["Ryan Levick <ryan.levick@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
serialize = ["serde", "serde_derive"]
